# Generated by Django 4.2.4 on 2023-11-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool", "0002_alter_marks_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentdetails",
            name="st_standard",
            field=models.IntegerField(default=9),
        ),
    ]
