# Generated by Django 4.2.4 on 2023-11-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool", "0004_unit_delete_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unit",
            name="id",
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_id",
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
