# Generated by Django 4.2.4 on 2023-11-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myschool", "0006_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_id",
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
